### ISSUE TITLE
link_read

### ISSUE THREAD

**Issue by digitalinferno** [FlatNuke/flatnuke#1]
Credo che in news_view.php ci sia qualcosa che non va con la funzione che restituisce il link per leggere la news, il risultato è un link a 'titolo.idnews' , che sembra non funzionare a differenza del vecchio codice che è stato disabilitato 'index.php?action=viewnews&news=idnews'

**Comment by marcosegato** [comment]
Questo problema è sicuramente da verificare, credo derivi dal tentativo di utilizzare l'URL rewriting tramite .htaccess (vedi changelog 4.0.0).

**Comment by bebabi34** [comment]
era un tentativo di utilizzare permalink, ma credo si scontri con la imprevedibilità di posizioni e quantità di sezioni news che si possono inserire in un sito. valutare se tornare ad un'unica sezione news meglio gestibile (script di upgrade a parte). oppure abbandonare (in mancanza di idee migliori) i permalink.

**Comment by bebabi34** [comment]
ho commentato le modifiche ripristinando il precedente funzionamento del link di lettura.
