### ISSUE TITLE
Admin: non salva modifiche configurazione

### ISSUE THREAD

**Issue by marcosegato** [FlatNuke/flatnuke#11]
Utilizzando gli strumenti della dashboard di amministrazione non sembra essere possibile effettuare il salvataggio delle modifiche, a dispetto del messaggio positivo di avvenuto aggiornamento.

**Comment by bebabi34** [comment]
ho provato un cambiamento di titolo e descrizione sito e sono stati salvati correttamente.
qualche dettaglio in più?

**Comment by marcosegato** [comment]
Fixed in de1e614
