### ISSUE TITLE
Warning utilizzo funzione date()

### ISSUE THREAD

**Issue by marcosegato** [FlatNuke/flatnuke#13]
Controllare il seguente warning che compare in svariate pagine:

Warning: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

Es:

/forum/include/archive.php on line 702
/functions.php on line 670

**Comment by bebabi34** [comment]
dov'è che compaiono questi avvisi? non no ho visti. mi fai un esempio specifico così provo.

**Comment by bebabi34** [comment]
mi sovviene che anni or sono avevo risolto un qualche problema del genere proprio indicando in php.ini
[Date]
date.timezone = "Europe/Rome"

quindi dipende dalle impostazioni php del server.
es. su altervista, phpinfo restituisce
Directive   Local Value Master Value
date.timezone   Europe/Rome Europe/Rome

se mi indichi qualche pagina che ha il problema provo a replicarlo in locale cambiando l'impostazione.

**Comment by marcosegato** [comment]
Con nuova installazione di PHP il problema è risolto; confermo che probabilmente si trattava di una configurazione particolare, chiudo.
