### ISSUE TITLE
Sezioni a utenti

### ISSUE THREAD

**Issue by arpierm** [FlatNuke/flatnuke#17]
Esiste la possibilità di far modificare una sezione a piu utenti con l'editor wysiwyg ??

**Comment by marcosegato** [comment]
Sì è possibile:
- accedi alla sezione come amministratore
- click su pulsante "Gestisci sezione"
- nel blocco "Permessi modifica" che compare puoi selezionare selettivamente i profili autorizzati

**Comment by arpierm** [comment]
Mi da questo errore quando tento di assegnare una sezione ad un utente registrato:
Fn_die: $mod is not a valid directory! functions.php: 3488

**Comment by marcosegato** [comment]
Su quale versione stai facendo la prova? 3.x o 4?

**Comment by arpierm** [comment]
ho un sito con FN 3.1.5 su server ergonet.it

**Comment by marcosegato** [comment]
Aperto segnalazione su FN3 in attesa di capire se anche su FN4 esista il problema.

**Comment by marcosegato** [comment]
Non riesco a riprodurre l'errore, funziona correttamente sia su 3.1.5 (verificato direttamente online sul sito ufficiale) che su 4.x
