### ISSUE TITLE
inibire le virgolette nella configurazione iniziale del titolo

### ISSUE THREAD

**Issue by bebabi34** [FlatNuke/flatnuke#18]
durante il setup se inserisco il carattere " nel titolo del sito (penso anche altrove) porto a termine la configurazione ma poi il sito non funziona.
soluzione 1. inibire l'utilizzo di " nella procedura di setup
soluzione 2. convertire i caratteri non standard inseriti nel setup

**Comment by marcosegato** [comment]
Fixed in 11364be
