### ISSUE TITLE
rinomina file non propone nome attuale

### ISSUE THREAD

**Issue by bebabi34** [FlatNuke/flatnuke#19]
nella funzione di rinomina di file html in sezioni, non viene proposto il nome attuale nel campo di inserimento (come avviene invece correttamente in caso di rinomina di sezioni: comodo).

altro comportamento diverso: i numeri a inizio nome per i file non sono visti some criterio di ordinamento, ma compaiono nel nome file printato a video (non così per le sezioni).
edit
ripensandoci quest'ultimo può andare bene. i file sono file e vanno mostrati così come sono all'interno di una sezione. magari convertire gli _ in spazi rende la schermata più gradevole.
comunque credo di poter risolvere questo issue. appena ho un attimo di calma, ravano.

**Comment by marcosegato** [comment]
Fixed in 5ecfa94
