### ISSUE TITLE
$sitedescription

### ISSUE THREAD

**Issue by digitalinferno** [FlatNuke/flatnuke#2]
In questa variabile troviamo la descrizione del sito, impostata nel pannello di controllo o durante l'installazione, ma se leggiamo una news restituisce come valore una preview della news stessa. Credo che sia da correggere. E' un problema presente anche nel vecchio ramo 3.x

**Comment by marcosegato** [comment]
In realtà questo effetto è voluto per una questione di SEO: avere lo stesso titolo per ogni pagina del sito è da considerarsi come penalizzante dal punto di vista del ranking, quindi si differenzia quanto più possibile.
- Nella home page ci sarà l'esatto contenuto di $sitedescription
- Nelle sezioni $sitedescription viene concatenata con il nome della sezione stessa
- Visualizzando una news, $sitedescription viene concatenata con il titolo della news stessa

O ti riferisci ad altro?

**Comment by digitalinferno** [comment]
No no, mi riferisco proprio a quello che elenchi. Ho notato questo comportamento aggiungendo degli heading con $sitename e $sitedescription. Non volendo naturalmente incidere negativamente sul SEO è possibile inserire una seconda variabile in modo da averne una per i temi con la descrizione del sito (uguale in qualunque pagina del sito) e una per il SEO da concatenare al titolo quando serve?

**Comment by marcosegato** [comment]
Nel commento precedente ho erroneamente parlato di **titolo** della pagina, ma in realtà stiamo parlando di **meta tag**: nel caso delle news, $sitedescription con una preview della notizia finisce nel meta tag "description"; anche il meta tag "keywords" contiene il nome della categoria sotto la quale è stata pubblicata la notizia stessa.
Questi contenuti non sono naturalmente visibili al visitatore, ed hanno il solo scopo di differenziare la pagina per i web crawler.
Tu quale effetto vorresti ottenere?

**Comment by digitalinferno** [comment]
In pratica nell'head invece di inserire un'immagine vorrei scrivere qualcosa tipo
`<h1>$sitename<h1/>`
`<h3>$sitedescription</h3>`
così chi usa il tema non ha bisogno di far altro che accedere al pannello di controllo e digitare quello che gli pare.

Per esempio FlatCry oggi è distribuito con il logo FlatNuke nell'head, chi vuole scrivere il nome del proprio sito deve usare per forza un programma di grafica (e spesso i risultati che ho visto in giro sono scadenti). Invece con l'aggiunta di webfont sarebbe un bel vedersi, anche per l'utente meno smaliziato.

Per $sitename funziona tutto perfettamente, per $sitedescription si verifica il problema esposto in apertura.

**Comment by marcosegato** [comment]
Ok, tutto chiaro: secondo me va creata una nuova variabile dedicata, che contenga il sottotitolo del sito, di modo da poterla utilizzare come dici tu.
Lo segno come possibile miglioria!

**Comment by bebabi34** [comment]
modificato header.php
[https://github.com/FlatNuke/flatnuke/commit/cb5e0025dfd2e8848cb942c373faad36c2c2c525]
dovrebbe bastare.
