### ISSUE TITLE
Cambiare riferimento sito progetto

### ISSUE THREAD

**Issue by marcosegato** [FlatNuke/flatnuke#22]
Il 21/09/2016 scadrà il dominio flatnuke.org e non verrà più rinnovato dalla persona che in tutti questi anni ci ha fatto questa gentile donazione.
Siccome credo che, visto lo stato attuale del progetto, non sia più così necessario un dominio di primo livello, occorrerà intervenire per sistituire i riferimenti a flatnuke.org per inserire flatnuke.netsons.org.
Nota: su Wikipedia ho già aggiornato tutto.

**Comment by digitalinferno** [comment]
Perchè non passare a un dominio di primo livello economico? TopHost per circa 5,99€ fornisce il dominio. Mi offro per il primo anno di pagamento.

**Comment by marcosegato** [comment]
Ciao Giovanni, per me va benissimo, e ti ringrazio molto per la tua offerta: se mi dai l'ok, ti metto in contatto con la persona che oggi gestisce il dominio e definite come fare il passaggio.
Il mio era anche un pensiero in prospettiva, per capire tra un anno cosa faremo; magari potremmo anche proporre una piccolissima raccolta per finanziare il rinnovo... vedremo.

**Comment by digitalinferno** [comment]
Beh una raccolta per le piccole spese credo sia un'ottima soluzione. Per il passaggio puoi pure procedere, ma non è meglio che l'intestazione rimanga a te o qualcuno dei dev principali?

**Comment by marcosegato** [comment]
Stiamo provando a fare il trasferimento su Tophost con contestuale riassegnazione del dominio a me, ti aggiorno.

**Comment by marcosegato** [comment]
Trasferimento dominio completato (senza cambio di intestatario, che al momento Tophost non supporta).
