### ISSUE TITLE
https

### ISSUE THREAD

**Issue by arpierm** [FlatNuke/flatnuke#27]
Ho un sito con fn3 sul quale ho richiesto l'Https. Per far si che quando si digiti www.miosito.com prenda in automatico https cosa debbo fare ? Grazie

**Comment by marcosegato** [comment]
Ciao, devi intervenire sulla configurazione del web server, Flatnuke non c'entra.
Per Apache trovi documentazione qui:
https://wiki.apache.org/httpd/RewriteHTTPToHTTPS
