### ISSUE TITLE
Statistiche discussioni forum

### ISSUE THREAD

**Issue by digitalinferno** [FlatNuke/flatnuke#28]
Se blocco un argomento le statistiche delle discussioni di quel argomento non vengono aggiornate in nessun caso. Credo che sia da correggere.

**Comment by bebabi34** [comment]
a quale/i statistiche ti riferisci? il contatore visite delle discussioni avanza. (ps se accedi come admin non vengono contate le tue visite)

**Comment by digitalinferno** [comment]
Il contatore visite della discussione avanza se blocco la discussione singola. Se blocco un argomento (in automatico tutte le discussioni di quel argomento vengono bloccate) e visito una discussione (da guest o utente) il contatore visite non si aggiorna. Questo comportamento è replicabile anche su altre versioni di FN (che probabilmente fanno uso sempre della stessa versione di FF).

**Comment by bebabi34** [comment]
capito. vero. controllo.
