### ISSUE TITLE
README con estensione md

### ISSUE THREAD

**Issue by bebabi34** [FlatNuke/flatnuke#3]
se si vuol lasciare l'estensione md al file README (scusa, ma a cosa serve?) va corretto il link del motd.php di benvenuto creato nell'installazione.
aprendo il file di testo la codifica del browser torna al default (non utf-8). come fare a cambiarla? (raw.github lo fa). altrimenti conviene lasciare il file README in ascii.

**Comment by bebabi34** [comment]
ho inviato (credo) il commit per correggere i link

**Comment by marcosegato** [comment]
L'estensione serve a GitHub per fare tutta una serie di cose automatiche come visualizzare il contenuto del file nella prima pagina del repository, nonché a creare automaticamente un sito con quel contenuto, ecc...

Non vedo un pull request per la modifica; ti ho aggiunti al team di sviluppo, basta che fai commit e push. Grazie della segnalazione.

**Comment by bebabi34** [comment]
quanto alla codifica. ho notato in .htaccess la specifica di utf-8 per i file di testo, ma i file .md non vengono riconosciuti come tali. ho aggiunto
AddType text/plain md
ma non sortisce effetti. invece richiamando
http://localhost/flatnuke/humans.txt
la codifica è utf-8.

**Comment by marcosegato** [comment]
Rilasciato fix 2bc6dc59d13a021b7172c769fbd33985204ca796
Attenzione: per vederne gli effetti occorre svuotare la cache del browser e riprovare.
