### ISSUE TITLE
Non incrementa le letture delle news

### ISSUE THREAD

**Issue by giorgiobis** [FlatNuke/flatnuke#33]
Sto usando con soddisfazione l'ultima 4.00 del 19 aprile 2017.
Sito partito da zero, non aggiornato da 3.1.5.

Pero` ho questo problema che non riesco a risolvere.

Grazie giorgio

**Comment by giorgiobis** [comment]
Grazie ragazzi, ho provato in tanti modi ma nisba...
Per fortuna ci siete voi.
Tutto ok
Grazie di nuovo.

**Comment by marcosegato** [comment]
Non so come mai, ma era proprio stato cancellato il richiamo alla funzione di incremento delle visualizzazioni. Un suggerimento: puoi utilizzare la versione precedente come base e confrontarne il codice, regressioni di questo tipo emergono più facilmente :-)
