### ISSUE TITLE
"download zip" di github non include le directory vuote

### ISSUE THREAD

**Issue by bebabi34** [FlatNuke/flatnuke#6]
il pacchetto scaricato da github omette le cartelle vuote. c'è modo di impostare un altro formato di archivio? altrimenti occorre aggiungere i soliti file .keepme o simili.

**Comment by marcosegato** [comment]
Ah grazie, non mi ero mai accorto che anche git si comportasse come cvs...
Bisogna reintrodurre i .keepme come giustamente dici.

**Comment by marcosegato** [comment]
Risolto con 8cdec01cb29be37feb514edd350a26306466ea3b
