### ISSUE TITLE
Notizie: Leggi tutto

### ISSUE THREAD

**Issue by giorgiobis** [FlatNuke/flatnuke#7]
Cliccando su **Leggi tutto**  in fondo alla notizia si viene mandati in pagina inesistente.
Mentre cliccando su **Commenti?** tutto ok.

Sito aggiornato dalla versione 3.1.5.

Grazie giorgio

**Comment by marcosegato** [comment]
Ciao Giorgio, grazie per la segnalazione: si tratta del problema segnalato con l'issue #1 già aperto.
