### ISSUE TITLE
I log non si vedono

### ISSUE THREAD

**Issue by giorgiobis** [FlatNuke/flatnuke#8]
Nel pannello di amministrazione **Gestione sicurezza -> Gestione log** non si vedono i log.
In **var/log** i log ci sono.
Grazie giorgio

**Comment by marcosegato** [comment]
ciao @giorgiobis ho provato su un'installazione partendo da zero e non rilevo alcun problema: i file ci sono e posso visualizzarli correttamente tramite pannello di amministrazione.
Puoi provare a controllare se ci sono errori nel log di Apache?
I file in var/log hanno i permessi di lettura impostati correttamente?

**Comment by giorgiobis** [comment]
Il sito e`ospitato su altervista, quindi i log di apache penso siano di altervista.
Ho provato l'installazione da zero ed e` ok.
Il problema nasce (forse) con l'upgrade dalla 3.1.5.
I file in var/log sono 664

Ho notato che nel pannello di amministrazione del sito passato dalla 3.1.5 in **Gestione sicurezza** posizionando il mouse su **Gestione log** il link e`:
javascript:jQueryFNcall('sections/none_Admin/section.php?mod=none_Admin&op=fncclogs','get','fn_adminpanel'); 

Mentre nel sito creato da zero:
javascript:jQueryFNcall('sections/none_Admin/section.php?mod=none_Admin&op=fncclogs','get','fncc-adminpanel');

In pratica cambia la parte finale del link
Io qui mi perdo

Grazie giorgio

**Comment by marcosegato** [comment]
@giorgiobis prova a sovrascrivere il file /sections/none_Admin/none_functions/func_interfaces.php, effettivamente manca nella procedura di upgrade.

**Comment by giorgiobis** [comment]
Provato:

_Fatal error: Call to undefined function fncc_main() in /membri/famiglieepace/include/autoexec.d/03_dashboard.php on line 55_

Grazie giorgio

**Comment by marcosegato** [comment]
Ho aggiornato il file UPGRADE con l'elenco delle cose da aggiornare per procedere con l'aggiornamento dalla 3.1.5 alla 4.0.0, purtroppo con i lavori della nuova dashboard non siamo stati abbastanza attenti...

Fix rilasciato: a0034ad5627890aec8ba534d3b8d66f4e602f09e
Facci sapere se risolvi, grazie.

**Comment by giorgiobis** [comment]
Fatto il nuovo upgrade:
ora ho la nuova versione della dashboard, i log si vedono e i link funzionano tutti.

Riscontro altri 2 problemi:
1) Il menù a sx è aperto completamente e cliccandoci sopra non si chiude (nel sito creato da zero ci sono 6 voci che cliccandoci sopra aprono un sottomenù; mentre nel sito passato dalla 3.1.5 le 6 voci sono tutte aperte e così rimangono).
2) A dx del menù ci sono 10 blocchi nel sito creato da zero;
nel sito passato dalla 3.1.5 manca **Server Info**, mentre **Statistiche di accesso** non è come grafico ma c'è un link all'anno 2016
_javascript:jQueryFNcall('sections/none_Admin/none_widgets/section.php?mod=none_Admin&year=2016','GET','year_chart');_
che non apre niente.

Grazie e buone feste, giorgio

**Comment by giorgiobis** [comment]
Scusa Marco, sono stato troppo precipitoso:
il menù a sx ora è ok.

Manca sempre il blocco **Server Info**.
Il blocco **Statistiche di accesso** ora si visualizza correttamente come grafico ma il link all'anno
_javascript:jQueryFNcall('sections/none_Admin/none_widgets/section.php?mod=none_Admin&year=2016','GET','year_chart');_ 
non apre niente.

Grazie e ri-buone feste, giorgio

**Comment by marcosegato** [comment]
Ciao Giorgio, se conti 10 blocchi allora "Server Info" deve esserci per forza: sulla destra ci sono 8 badge + 2 blocchi ("Server Info" appunto e "Statistiche di accesso").
![Flatnuke Dashboard 4.0.0-dev](https://cloud.githubusercontent.com/assets/6240628/14053427/73e6956e-f2d1-11e5-8430-00c08e768589.png)

Per le statistiche hai ragione, ci sono degli errori: apro un nuovo issue perché il widget è completamente da riscrivere...
Grazie e buone feste a te :)

**Comment by giorgiobis** [comment]
I 10 blocchi li vedo quando carico il sito costruito da zero (come la tua immagine).

Quando invece carico il sito aggiornato dalla 3.1.5 manca proprio Server Info, che però riesco ad aprire dal menù di sinistra **Opzioni Flatnuke** -> **Informazioni server** che mi da questo link:
_javascript:jQueryFNcall('sections/none_Admin/section.php?mod=none_Admin&op=fnccinfo','get','fncc-adminpanel');_

Grazie giorgio

**Comment by marcosegato** [comment]
E' molto strano, perché è tutto dentro lo stesso file section.php, quindi a rigor di logica mi viene da dire "o tutto o niente" :)
Potresti provare a ricaricare questi file come da UPGRADE?
- sections/none_Admin/none_widgets/*.xml
- sections/none_Admin/none_widgets/*.php

Se ancora non va non saprei, potrebbe non leggere i file XML (che corrispondono ai blocchi mancanti, guarda caso), ma a questo punto potrebbe essere un problema di web server...

**Comment by giorgiobis** [comment]
Hai perfettamente ragione, non avevo caricato _**00_server_info.php**_ e _**00_server_info.xml**_

Tutto ok

Grazie giorgio

**Comment by marcosegato** [comment]
Perfetto, grazie per la conferma.
