### ISSUE TITLE
Dashboard: widget statistiche non cambia anno

### ISSUE THREAD

**Issue by marcosegato** [FlatNuke/flatnuke#9]
Da: https://github.com/FlatNuke/flatnuke/issues/8#issuecomment-201172644
Il link all'anno non apre niente.

Problemi da correggere:
- url ajax non corretto che punta a section.php invece che al file del widget
- widget non rispecchia standard previsti in quanto parte del codice è nel section.php principale; occorre separare nettamente le due logiche

**Comment by marcosegato** [comment]
Fixed: bcfc3283aef272ed86dedbffbcdbb911d432f4c9
@giorgiobis devi aggiornare "section.php" e "05_year_stats.php" nella cartella "sections/none_Admin/none_widgets/"

**Comment by giorgiobis** [comment]
Scusa Marco del tardivo riscontro, ma ho voluto provare e riprovare.
Ho aggiornato come da tuo consiglio... ma niente.
Allora mi sono scaricato nuovamente tutto lo zip e rifatto l'upgrade dal 3.1.5

I problemi nel pannello di amministrazione rimangono 2:
1) il menu a sinistra è e rimane aperto (come da foto) e ovviamente non è visibile e non scrollabile la parte inferiore;
2) l'anno delle Statistiche, cliccandoci sopra, questo il link:

_javascript:jQueryFNcall('sections/none_Admin/none_widgets/05_year_stats.php?mod=none_Admin&year=2016','GET','year_chart');_

si muove ma non apre ancora niente.

![bacheca_fnluke](https://cloud.githubusercontent.com/assets/17708468/14940487/30ad281c-0f78-11e6-8556-0dc1b8ec3eb5.jpg)
